//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividades()
        {
            this.Paga = new HashSet<Paga>();
        }
    
        public string nomeParque { get; set; }
        public int númeroSequencial { get; set; }
        public int ano { get; set; }
        public string nome { get; set; }
        public string descrição { get; set; }
        public Nullable<int> lotaçãoMáxima { get; set; }
        public Nullable<int> preçoParticipante { get; set; }
        public Nullable<System.DateTime> dataRealização { get; set; }
    
        public virtual ParqueCampismo ParqueCampismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paga> Paga { get; set; }
    }
}
