//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamento()
        {
            this.AlojamentoEstada = new HashSet<AlojamentoEstada>();
            this.Extra = new HashSet<Extra>();
        }
    
        public string nomeParque { get; set; }
        public string nome { get; set; }
        public string localização { get; set; }
        public string descrição { get; set; }
        public Nullable<int> preçoBase { get; set; }
        public Nullable<byte> númeroMáximoPessoas { get; set; }
        public string tipoAlojamento { get; set; }
    
        public virtual ParqueCampismo ParqueCampismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlojamentoEstada> AlojamentoEstada { get; set; }
        public virtual Bungalow Bungalow { get; set; }
        public virtual Tenda Tenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extra> Extra { get; set; }
    }
}
