//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bungalow
    {
        public string nomeParque { get; set; }
        public string localização { get; set; }
        public string tipologia { get; set; }
    
        public virtual Alojamento Alojamento { get; set; }
    }
}
