//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estada()
        {
            this.AlojamentoEstada = new HashSet<AlojamentoEstada>();
            this.EstadaExtra = new HashSet<EstadaExtra>();
            this.HóspedeEstada = new HashSet<HóspedeEstada>();
        }
    
        public int id { get; set; }
        public System.DateTime dataInício { get; set; }
        public System.DateTime dataFim { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> ano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlojamentoEstada> AlojamentoEstada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadaExtra> EstadaExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HóspedeEstada> HóspedeEstada { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
