//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paga
    {
        public string nomeParque { get; set; }
        public int númeroSequencial { get; set; }
        public int ano { get; set; }
        public int NIF { get; set; }
        public Nullable<int> preçoParticipante { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Hóspede Hóspede { get; set; }
    }
}
